name: Build Docs

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install doc dependencies
        run: |
          pip install sphinx sphinx-autodoc-typehints sphinx-rtd-theme matplotlib
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs # The branch the action should deploy to.
          folder: docs/_build/html # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
