name: Build Docs

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install doc dependencies
        run: |
          pip install sphinx sphinx-autodoc-typehints sphinx-rtd-theme matplotlib
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs # The branch the action should deploy to.
          FOLDER: docs/_build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
