name: Release Windows Exec
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install wheel pyinstaller
          pip install .
          python setup.py build_ext --inplace
    - name: Build exec
      id: build-exec
      run: |
        pyinstaller --clean -y pewpew.spec
    - name: Set output version
      id: set-output
      run : |
        echo "PEWPEW_VERSION=$(python -c "from importlib.metadata import version; print(version('pewpew'))")" >> "$env:GITHUB_OUTPUT"
    - name: Upload binary
      id: upload
      run: |
        gh release upload "$env:TAG_NAME" "./dist/pewpew_$env:PEWPEW_VERSION.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PEWPEW_VERSION: ${{ steps.set-output.outputs.PEWPEW_VERSION }}
        TAG_NAME: ${{ github.event.release.tag_name }}
